[project]
name = "daily-email-report"
version = "0.1.0"
description = "This project creates a daily headlines report and stock market report for email delivery."
readme = "README.md"
requires-python = ">=3.12.11"
dependencies = [
    "feedparser>=6.0.12",
    "groq>=1.1.2",
    "python-dotenv>=1.2.2",
]
